if (A_Language = "0804")
{
    global _Author="知阳"
    global _Exit="退出 Power Keys"
    global _Restart="重启 Power Keys"
    global _Updating="正在更新 Power Keys"
    global _EnableSpace="启用空格编辑【Caps Lock + Space】"
    global _DisableSpace="禁用空格编辑【Caps Lock + Space】"
    global _EnableGameMode="启用游戏模式【Win + Esc】"
    global _DisableGameMode="禁用游戏模式【Win + Esc】"
    global _StartUp="开机自启"
    global _Config="配置光速启动【F1 ~ F12 + Enter】"
    global _Help="帮助文档【Win + F1】"
    global _Feedback="报告问题 / 反馈建议"
    global _OfficialQQ="请加入 Power Keys 官方 QQ 群 959910853`n以报告问题或反馈建议。"
    global _Update="更新 Power Keys"
    global _ConfirmEmptyRecycleBin="确定清空回收站？"
    global _Require64="请使用 64 位版本。"
    global _SpaceEnabled="已启用空格编辑"
    global _SpaceDisabled="已禁用空格编辑"
    global _GameModeEnabled="已启用游戏模式"
    global _GameModeDisabled="已禁用游戏模式"
    global _PoorNetwork="与 GitHub 连接不畅！请稍后再试。"
    global _ConfirmExit="遇到问题？请尝试下列解决方法！`n`n1. 阅读帮助文档`n2. 启用游戏模式`n3. 重启 Power Keys`n4. 更新 Power Keys`n5. 反馈您的问题`n`n仍然退出 Power Keys？"
}
else
{
    global _Author="szzhiyang"
    global _Exit="Exit Power Keys"
    global _Restart="Restart Power Keys"
    global _Update="Update Power Keys"
    global _Updating="Updating Power Keys"
    global _EnableSpace="Enable Power Space【Caps Lock + Space】"
    global _DisableSpace="Disable Power Space【Caps Lock + Space】"
    global _EnableGameMode="Enable Game Mode【Win + Esc】"
    global _DisableGameMode="Disable Game Mode【Win + Esc】"
    global _StartUp="Run At Startup"
    global _Config="Configure Flash Launch【F1 ~ F12 + Enter】"
    global _Help="Help File【Win + F1】"
    global _Feedback="Report Bugs / Make Suggestions"
    global _OfficialQQ="To report bugs or make suggestions,`nplease join Power Keys Offical QQ group 959910853."
    global _ConfirmEmptyRecycleBin="Clear recycle bin?"
    global _Require64="Please use the 64-bit version."
    global _SpaceEnabled="Power Space Enabled"
    global _SpaceDisabled="Power Space Disabled"
    global _GameModeEnabled="Game Mode Enabled"
    global _GameModeDisabled="Game Mode Disabled"
    global _PoorNetwork="Poor connection with GitHub! Please try again later."
    global _ConfirmExit="Encountered an issue? Please try these solutions!`n`n1. Read the help file`n2. Enable Game Mode`n3. Restart Power Keys`n4. Update Power Keys`n5. Report the issue`n`nExit Power Keys anyway?"
}