if (A_Language = "0804")
{
    global _Author="知阳"
    global _Exit="退出 Power Keys"
    global _Restart="重启 Power Keys"
    global _Updating="正在更新 Power Keys"
    global _EnableSpace="启用空格编辑 | Caps Lock + Space"
    global _DisableSpace="禁用空格编辑 | Caps Lock + Space"
    global _EnableGameMode="启用游戏模式 | Win + Esc"
    global _DisableGameMode="禁用游戏模式 | Win + Esc"
    global _StartUp="开机自启"
    global _Config="配置光速启动 | F1 ~ F12 + Enter"
    global _Help="帮助文档 | Win + F1"
    global _Feedback="反馈问题"
    global _Update="更新 Power Keys"
    global _ConfirmEmptyRecycleBin="确定清空回收站？"
    global _Require64="请使用 64 位版本。"
    global _SpaceEnabled="已启用空格编辑"
    global _SpaceDisabled="已禁用空格编辑"
    global _GameModeEnabled="已启用游戏模式"
    global _GameModeDisabled="已禁用游戏模式"
    global _PoorNetwork="与 GitHub 连接不畅！请稍后再试。"
    global _ConfirmExit="遇到问题？`n`n请逐一尝试下列解决方法！`n`n1. 禁用杀毒软件`n2. 通读帮助文档`n3. 启用游戏模式`n4. 重启 Power Keys`n5. 更新 Power Keys`n6. 加入 QQ 群 959910853 反馈问题`n`n仍然退出 Power Keys？"
    global _ConfirmFeedback="请逐一尝试下列解决方法！`n`n1. 退出杀毒软件`n2. 仔细通读帮助文档`n3. 启用游戏模式`n4. 重启 Power Keys`n5. 更新 Power Keys`n6. 加入 QQ 群 959910853 反馈问题"
}
else
{
    global _Author="szzhiyang"
    global _Exit="Exit Power Keys"
    global _Restart="Restart Power Keys"
    global _Update="Update Power Keys"
    global _Updating="Updating Power Keys"
    global _EnableSpace="Enable Power Space | Caps Lock + Space"
    global _DisableSpace="Disable Power Space | Caps Lock + Space"
    global _EnableGameMode="Enable Game Mode | Win + Esc"
    global _DisableGameMode="Disable Game Mode | Win + Esc"
    global _StartUp="Run At Startup"
    global _Config="Configure Flash Launch | F1 ~ F12 + Enter"
    global _Help="Help File | Win + F1"
    global _Feedback="Report Bugs"
    global _ConfirmEmptyRecycleBin="Clear recycle bin?"
    global _Require64="Please use the 64-bit version."
    global _SpaceEnabled="Power Space Enabled"
    global _SpaceDisabled="Power Space Disabled"
    global _GameModeEnabled="Game Mode Enabled"
    global _GameModeDisabled="Game Mode Disabled"
    global _PoorNetwork="Poor connection with GitHub! Please try again later."
    global _ConfirmExit="Encountered an issue? `n`nPlease try these solutions one by one!`n`n1. Disable the anti-malware software`n2. Read the help file throughly`n3. Enable Game Mode`n4. Restart Power Keys`n5. Update Power Keys`n6. Join QQ group 959910853 to report the issue`n`nExit Power Keys anyway?"
    global _ConfirmFeedback="Please try these solutions one by one!`n`n1. Disable the anti-malware software`n2. Read the help file throughly`n3. Enable Game Mode`n4. Restart Power Keys`n5. Update Power Keys`n6. Join QQ group 959910853 to report the issue"
}